from pathlib import Path

plan_content = '''# Implementation Plan: Frontend Routing Architecture

**Branch**: `master` | **Date**: 2026-06-01 | **Spec**: [specs/002-routing-architecture/spec.md](./spec.md)

**Input**: Feature specification from `specs/002-routing-architecture/spec.md`

**Note**: This plan file is generated by the `/speckit.plan` command.

## Summary

Replace the existing Component Preview Server in `src/App.tsx` with a real client-side route architecture powered by `react-router-dom`.
The plan preserves all existing mockup screens under `src/components/mockups/serv-table`, wires them to explicit customer and admin paths, and prepares the frontend structure for future API integration.

## Technical Context

**Language/Version**: TypeScript 6.0 with React 19.2 (`tsconfig.json`, Vite)

**Primary Dependencies**:
- `react`, `react-dom`
- `react-router-dom` 7.16
- `@tanstack/react-query`
- `react-hook-form`
- `zod`
- `tailwindcss`
- `lucide-react`

**Storage**: N/A for initial routing work; the focus is on client-side route composition and UI reuse.

**Testing**: Vite dev server, TypeScript compile, and ESLint linting. No dedicated frontend test framework is currently present in the repository.

**Target Platform**: Web browser SPA.

**Project Type**: Frontend web application.

**Performance Goals**:
- Client-side route changes with no full page reload.
- Preserve current mockup performance and visual fidelity.

**Constraints**:
- Must preserve existing mockup UI without redesign.
- Must not retain the Component Preview Server behavior.
- Must preserve the existing page files as reusable route screens.

**Scale/Scope**:
- Single frontend app with a customer area and an admin area.
- Ten existing routeable pages plus route variants.

## Constitution Check

The plan is aligned with the ServTable constitution:
- Separation of Concerns: routing logic is isolated in `src/App.tsx` and `src/routes`, while page components remain presentation-focused.
- Type Safety: the route layer uses TypeScript types and explicit imports.
- Reusable Components & Hooks: existing UI screens are reused, and no UI redesign is required.
- Service Layer Architecture: this phase does not add backend calls in components; future API integration is prepared through service folder scaffolding.
- Maintainability: the plan recommends a stable route layout and gradual migration path to `src/pages` and `src/layouts`.
- Tooling & Standards: uses existing React Router dependency and preserves current build tooling.

**Gate Verdict**: No constitution violations are introduced by the routing plan. The proposed architecture preserves separation of concerns and keeps business logic out of components.

## Project Structure

### Existing Relevant Layout

```text
src/
├── App.tsx
├── components/
│   ├── mockups/serv-table/    # existing page screens reused by routes
│   └── ui/                    # reusable UI primitives and components
├── hooks/
│   ├── useCreateDish.ts
│   ├── useDeleteDish.ts
│   ├── useDishes.ts
│   └── useUpdateDish.ts
├── services/
│   └── dishes/
│       ├── dishService.ts
│       └── schemas.ts
└── index.css
```

### Proposed Routing-Focused Structure

```text
src/
├── App.tsx
├── routes/
│   ├── AppRoutes.tsx
│   └── routeConstants.ts
├── layouts/
│   ├── AdminLayout.tsx
│   └── CustomerLayout.tsx
├── pages/                    # optional future migration target
│   ├── customer/
│   └── admin/
├── components/
│   ├── mockups/serv-table/
│   └── ui/
├── hooks/
└── services/
```

### Structure Decision

The route layer will be introduced without immediately moving the existing mockup files. `src/components/mockups/serv-table` remains the source of truth for the current page UI, while `src/routes` and `src/layouts` provide the new routing and layout scaffolding.
This minimizes disruption and preserves the exact look and feel of existing pages.

## Route Definitions

### Customer Routes
- `/` → `CustomerHome`
- `/buffet` → `CustomerBuffetHome`
- `/dish/:id` → `DishDetails`
- `/dish/:id/v2` → `DishDetailsV2`

### Admin Routes
- `/admin` → `Dashboard`
- `/admin/dashboard` → `Dashboard`
- `/admin/cardapio` → `GerenciamentoCardapio`
- `/admin/cardapio/novo` → `CadastroPrato`
- `/admin/cardapio/form` → `CadastroPratoForm`
- `/admin/pedidos` → `Orders`
- `/admin/imagens` → `AtualizacaoImagens`
- `/admin/imagens/buffet` → `GestaoImagensBuffet`
- `/admin/buffet` → `OrganizacaoBuffet`
- `/admin/buffet/dnd` → `OrganizacaoBuffetDnD`

## Routing Implementation Notes

- `src/App.tsx` becomes the router entrypoint with `BrowserRouter`.
- Route definitions should be extracted into `src/routes/AppRoutes.tsx`.
- Common admin and customer layouts should be implemented in `src/layouts/`.
- Navigation anchors using `href="#"` should be replaced with `Link` or `NavLink`.
- `DishDetailsV2` is preserved through a dedicated route variant so the existing page remains accessible.

## Phase 0 Research Output

The research artifact identifies the core architecture decision: replace preview mode with `react-router-dom` and retain existing page UI.

## Phase 1 Design Output

- `research.md` was created with routing decisions and accepted alternatives.
- `data-model.md` was created with route and page models.
- `quickstart.md` was created with implementation steps.
- `contracts/frontend-routing.md` was created to define the route interface contract.

## Complexity Tracking

No constitution violations or additional architectural complexity were introduced. The plan remains within the defined frontend routing scope.
'''

instructions_content = '''<!-- SPECKIT START -->
**Current Feature**: Frontend Routing Architecture
**Plan**: [specs/002-routing-architecture/plan.md](../specs/002-routing-architecture/plan.md)
**Design Artifacts**:
- [Feature Specification](../specs/002-routing-architecture/spec.md)
- [Research & Decisions](../specs/002-routing-architecture/research.md)
- [Data Model](../specs/002-routing-architecture/data-model.md)
- [Routing Contract](../specs/002-routing-architecture/contracts/frontend-routing.md)
- [Developer Quickstart](../specs/002-routing-architecture/quickstart.md)

**Tech Stack**: React 19.2, TypeScript, React Router, React Query, React Hook Form, Zod, Tailwind
**Architecture**: BrowserRouter route layer + existing mockup route pages
<!-- SPECKIT END -->
'''

Path(r'd:\projetos\serv-table\frontend\servtable\specs\002-routing-architecture\plan.md').write_text(plan_content, encoding='utf-8')
Path(r'd:\projetos\serv-table\frontend\servtable\.github\copilot-instructions.md').write_text(instructions_content, encoding='utf-8')
